#!/usr/bin/env python3
"""
GymHappy MCP Installer for Claude Desktop
Generated by PushPress Team Plugin — /pp-setup-gymhappy

Run once from Terminal:
    python3 install-gymhappy-mcp.py

Adds GymHappy to Claude Desktop so you get GymHappy tools there too,
not just in Cowork. Safe to re-run — backs up your config first.
"""
import json, os, shutil

print("GymHappy MCP Installer")
print("=" * 40)
print()
print("Get your token at: https://app.gymhappy.co/super/mcp-token")
print()
token = input("Paste your GymHappy token: ").strip()
if not token:
    print("❌  No token provided. Exiting.")
    exit(1)

# Ensure | is encoded as %7C (required by CloudFront)
token = token.replace("|", "%7C")

config_path = os.path.expanduser(
    "~/Library/Application Support/Claude/claude_desktop_config.json"
)

if not os.path.exists(config_path):
    print()
    print("❌  Claude Desktop config not found.")
    print(f"   Expected: {config_path}")
    print("   Make sure Claude Desktop is installed and has been opened at least once.")
    exit(1)

# Backup
backup = config_path + ".backup"
shutil.copy2(config_path, backup)
print(f"✅  Backed up existing config → {backup}")

# Read
with open(config_path) as f:
    config = json.load(f)

# Merge GymHappy entry
# NOTE: Token goes in the URL as a query param — CloudFront strips Authorization headers,
# which causes 401 → OAuth trigger → 419. Query param bypasses this entirely.
config.setdefault("mcpServers", {})["gymhappy-support"] = {
    "command": "npx",
    "args": [
        "-y", "mcp-remote",
        f"https://app.gymhappy.co/mcp/support?mcp_token={token}"
    ]
}

# Write back safely
tmp = config_path + ".tmp"
with open(tmp, "w") as f:
    json.dump(config, f, indent=2)
    f.write("\n")
os.replace(tmp, config_path)

print("✅  GymHappy MCP added to Claude Desktop!")
print()
print("👉  Restart Claude Desktop for it to take effect.")
print("    Then try: \'Look up [gym name]\'")
